var i18n = $.extend({}, i18n || {}, {
    xgcalendar: {
        dateformat: {
            "fulldaykey": "ddMMyyyy",
            "fulldayshow": "d.M.yyyy",
            "fulldayvalue": "M/d/yyyy",
            "Md": "W d.M",
            "Md3": "d.M.yyyy",
            "separator": "/",
            "year_index": 2,
            "month_index": 0,
            "day_index": 1,
            "day": "d",
            "sun": "su",
            "mon": "ma",
            "tue": "ti",
            "wed": "ke",
            "thu": "to",
            "fri": "pe",
            "sat": "la",
            "jan": "tammikuu",
            "feb": "helmikuu",
            "mar": "maaliskuu",
            "apr": "huhtikuu",
            "may": "toukokuu",
            "jun": "kes�kuu",
            "jul": "hein�kuu",
            "aug": "elokuu",
            "sep": "syyskuu",
            "oct": "lokakuu",
            "nov": "marraskuu",
            "dec": "joulukuu"
        },
        "no_implemented": "No implemented yet",
        "to_date_view": "Click to the view of current date",
        "i_undefined": "Undefined",
        "allday_event": "Koko p�iv�n tapahtuma",
        "repeat_event": "Toista tapahtuma",
        "time": "Aika",
        "event": "Tapahtuma",
        "location": "Paikka",
        "participant": "Osallistuja",
        "get_data_exception": "Exception when getting data",
        "new_event": "New event",
        "confirm_delete_event": "Do you confirm to delete this event? ",
        "confrim_delete_event_or_all": "Do you want to all repeat events or only this event? \r\nClick [OK] to delete only this event, click [Cancel] delete all events",
        "data_format_error": "Data format error! ",
        "invalid_title": "Event title can not be blank or contains ($<>)",
        "view_no_ready": "View is not ready",
        "example": "esim. tapaaminen huoneessa 107",
        "content": "Otsikko",
        "create_event": "Luo tapahtuma",
        "update_detail": "Muokkaa tietoja",
        "click_to_detail": "Tarkastele tietoja",
        "i_delete": "Poista",
        "day_plural": "p�iv��",
        "others": "Others",
        "item": ""
    }
});
